- name: prepare some dirs
  file: name={{base_dir}}/manifests/prometheus/setup state=directory

#- name: 判断是否已经部署prometheus
#  shell: "{{ bin_dir }}/kubectl get pods -n monitoring | wc -l"
#  register: ok_var
#  when: cs_monitor_enable == true

#- name: show debug info
#  debug: var=ok_var.stdout  verbosity=0

#- name: 删除已经部署的pods 和deployment
#  shell: "{{ bin_dir }}/kubectl delete all  --all -n monitoring --force --grace-period=0"
#  when: ok_var.stdout | int  > 0 and is_force_reinstall == true 

#- name: 删除manifest文件
#  shell: "rm -rf {{ base_dir }}/manifests/prometheus/"
#  when:  ok_var.stdout | int  > 0 and is_force_reinstall == true

- name: 创建组件模板文件
  template: src={{ item }} dest={{ base_dir }}/manifests/prometheus/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob:
    - "{{base_dir}}/roles/gpaas/monitor/prometheus/templates/*"
  when: cs_monitor_enable == true and is_force_reinstall == true

- name: 创建CRD模板文件 
  template: src={{ item }} dest={{ base_dir }}/manifests/prometheus/setup/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob:
    - "{{base_dir}}/roles/gpaas/monitor/prometheus/templates/setup/*"
  when: cs_monitor_enable == true and is_force_reinstall == true

- name: 复制非模板CRD文件
  copy: src={{ item }} dest={{ base_dir }}/manifests/prometheus/setup/{{ item | basename  }}
  with_fileglob:
    - "{{base_dir}}/roles/gpaas/monitor/prometheus/files/setup/*"
  when: cs_monitor_enable == true and is_force_reinstall == true

- name: 复制非模板部署文件
  copy: src={{ item }} dest={{ base_dir }}/manifests/prometheus/{{ item | basename }}
  with_fileglob:
    - "{{base_dir}}/roles/gpaas/monitor/prometheus/files/*"
  when: cs_monitor_enable == true and is_force_reinstall == true

- name: 部署CRD
  shell: "{{ bin_dir }}/kubectl apply -f {{ base_dir }}/manifests/prometheus/setup"
  when: cs_monitor_enable == true 


- name: 部署 组件
  shell: "{{ bin_dir }}/kubectl apply -f {{ base_dir }}/manifests/prometheus/"
  when: cs_monitor_enable == true

