# 所有主机进行基础环境配置
#- hosts: all
#  gather_facts: yes

- hosts:
  - kube-cluster
  - deploy
  roles:
  - kubernetes/os-env

#- hosts: kube-storage-node
#  tasks:
#    - name: 检测存储节点中是否存在指定的磁盘设备
#      fail:
#        msg: "存储节点中找不到指定的磁盘设备"
#      when: 'ansible_devices[gfs_device|replace("/dev/","")] is not defined'
